[package]
name = "clim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
clearscreen = "2.0.1"
dialoguer = "0.10.4"
figlet-rs = "0.1.5"
